version: 2.1
jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.1-node



    steps:
      - checkout
      - run: cd my-app
      - run: ls
      - run: yarn install
      - run: yarn test

Workflows:
  test:
    jobs:
      - buildcd ls