version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers



    steps:
      - checkout
      - run: cd my-app && npm install --save
      - run: cd my-app && npm run test
      - store_test_results:
          path: test-results

Workflows:
  test:
    jobs:
      - build


